### ISSUE TITLE
算是bug吧

### ISSUE THREAD

**Issue by rqil** [pure-music/PureMusic#1]
长按切换上一首或者下一首会从头开始播放。

**Comment by Caij** [comment]
@rqil  长按什么地方切换的

**Comment by rqil** [comment]
播放页面长按左右箭头

**Comment by rqil** [comment]
还有一个是返回键好像是全都无效，是不是还没有完成呀？另外，如果可以的话，稍微加点对TV遥控器操控的支持呗。

**Comment by Caij** [comment]
你说的这两个问题已经发布新版解决，可以到release列表下载
