### ISSUE TITLE
发现有些flac格式的音频无法读取歌词

### ISSUE THREAD

**Issue by 99477204** [pure-music/PureMusic#10]
音乐已内嵌歌词，flac格式，有的可以正常显示歌词，有些显示找不到歌词

**Comment by Caij** [comment]
把文件分享一下给我  加tg或者qq群 或者搞个云盘

**Comment by 99477204** [comment]
> 把文件分享一下给我 加tg或者qq群 或者搞个云盘
可以了又好了
