### ISSUE TITLE
关于PC界面的优化建议

### ISSUE THREAD

**Issue by HumanMus1c** [pure-music/PureMusic#12]
因为目前暂时不能更改主题颜色，只能白色的状态下容易和其他系统Windows界面或其他软件界面混淆，不方便辨别软件的边界及定位。
（也可能是我的显示器色域太差了）希望未来可以更改主题颜色以及添加窗口边框有色描边。
![image](https://github.com/pure-music/PureMusic/assets/46023154/165622ab-f0a2-4e68-afa9-bc9a24fd4aa1)
![image](https://github.com/pure-music/PureMusic/assets/46023154/bc125434-6111-444d-8dfd-e90bc5e8d430)

**Comment by HumanMus1c** [comment]
如果软件的字体能够自定义就更好了。

**Comment by Caij** [comment]
页面阴影已经支持，字体短时间不会考虑
