### ISSUE TITLE
请求专辑页添加随机播放按钮

### ISSUE THREAD

**Issue by ironstress** [pure-music/PureMusic#14]
功能:随机一张专辑播放

**Comment by Caij** [comment]
专辑列表？

**Comment by ironstress** [comment]
> 专辑列表？

是的

**Comment by Caij** [comment]
最新beta版本已经支持

**Comment by ironstress** [comment]
> 最新beta版本已经支持

版本: [v1.38.0-beta4](https://github.com/pure-music/PureMusic/releases/tag/v1.38.0-beta4) 
随机播放一张专辑, 播放模式会强制变成"随机", 播放的这张专辑是乱序的.
