### ISSUE TITLE
关于专辑的三个BUG

### ISSUE THREAD

**Issue by ironstress** [pure-music/PureMusic#15]
环境: PureMusic_v1.36.12_windows_x86_64 ; emby音乐库
1.
播放某一张专辑时, 点击"播放全部", 除了track1会固定在播放列表里第一个, 其他的track是乱序的.
![image](https://github.com/user-attachments/assets/86ed56f8-d7e3-47e8-bd89-0691b33f2346)
2.
歌手页, 专辑列表无法通过鼠标拖动/滚轮滚动.
建议添加按钮跳转到一个页面, 为演出者的专辑列表.
![image](https://github.com/user-attachments/assets/b472e66d-2aa3-4e88-99db-bb70af69e228)
3.
无法区分多张disc的专辑
![image](https://github.com/user-attachments/assets/2c40457f-26bb-4af4-a3c7-57eec0830b9a)

**Comment by Caij** [comment]
1的问题你有开随机模式吗

**Comment by ironstress** [comment]
> 1的问题你有开随机模式吗

是的, 是因为随机模式, 
改成顺序模式解决了

**Comment by Caij** [comment]
你的emby源方便借我测试disc不， 方便的话可以去app关于里面加qq群  或者email我  dev.caij@gmail.com

**Comment by ironstress** [comment]
> 你的emby源方便借我测试disc不， 方便的话可以去app关于里面加qq群 或者email我 [dev.caij@gmail.com](mailto:dev.caij@gmail.com)

已发邮箱

**Comment by Caij** [comment]
发了一个beta版本 可以试试

**Comment by ironstress** [comment]
> 发了一个beta版本 可以试试

好啊, 问题2和问题3都解决了. 

不过, 我看更新日志写的是"优化桌面版横滑操作体验", 但是我只看到"更多"的按钮, 并不能滑动

**Comment by Caij** [comment]
滑动问题windows的不好处理，先这样了
