### ISSUE TITLE
onedrive也是播放到哪首才由软件缓存封面的吗？

### ISSUE THREAD

**Issue by iwvw** [pure-music/PureMusic#16]
我记得onedrive的api有提供缩略图，可不可以直接用onedrive自带的缩略图，省去软件缓存？

https://learn.microsoft.com/zh-cn/onedrive/developer/rest-api/api/driveitem_list_thumbnails?view=odsp-graph-online

**Comment by Caij** [comment]
是有的，之前有记录这个数据，但是判断是有一些问题可能导致部分数据缺失，下个版本修复可以关注内测版和正式版
