### ISSUE TITLE
希望增加对有声书的支持

### ISSUE THREAD

**Issue by bearduncle520** [pure-music/PureMusic#17]
用了很多播放器，对有声书很好支持的不多。可能像我这种想用音乐播放器听有声书的比较少数，毕竟因为播放器好看很多。
目前市面上的有声书app都不能导入本地和第三方。而音乐播放器界面好看，但是对有声书支持却不是很友好。
梳理了下有声书的需求，其实就三个方面。
一是跳过头尾功能，精确到0.5秒这种，因为很多有声书都有片头和片尾；
二是倍速功能，也是紧缺到0.5倍速，特别是1.75倍速，很多都没有；
三是定时关闭，大多数是按时长关闭，没有以几首歌或者几节有声书为单位的。
不知道开发者有没有以上计划，可能这种需求真的是少数。

**Comment by Caij** [comment]
1  暂无计划支持，因为音乐的片头片尾app无法识别，无法精准跳过。
2 倍速播放播放页面可以自己填写, 填写0-3内的值都是可以的。
3 最新内测版定时新增了播放多少首歌曲停止
https://github.com/pure-music/PureMusic/releases/tag/v1.40.0-beta.7
