### ISSUE TITLE
适配墨·状态栏歌词

### ISSUE THREAD

**Issue by CGBB0** [pure-music/PureMusic#2]
-![Screenshot_2023-06-28-00-49-40-753_org.lsposed.manager.jpg](https://github.com/pure-music/PureMusic/assets/101496448/0a2f9b7d-f7f1-43c2-93bc-6c22d990c059)

**Comment by Caij** [comment]
@CGBB0 请尝试最新版应该已经解决  https://github.com/pure-music/PureMusic/releases

**Comment by CGBB0** [comment]
完美✓
