### ISSUE TITLE
歌词与翻译识别错误

### ISSUE THREAD

**Issue by CGBB0** [pure-music/PureMusic#3]
![IMG_20230629_155639.jpg](https://github.com/pure-music/PureMusic/assets/101496448/3fb0fa3e-3638-4ff0-b00f-dd7071765bdc)

![IMG_20230629_155822.jpg](https://github.com/pure-music/PureMusic/assets/101496448/bfc435ef-f30a-42a1-a998-4b507324d52c)
这是歌词lrc的格式，上面的是歌词，下面的是翻译，对应的歌词与翻译时间轴相同。

当然这个问题不修也行，我后面计划把翻译都删掉，我也用不着翻译。

**Comment by Caij** [comment]
@CGBB0 后续解决

**Comment by Caij** [comment]
@CGBB0 能发一份文件给我吗 我方便测试

**Comment by CGBB0** [comment]
https://wwso.lanzouj.com/iIciF10rjetg
这里面包含外挂歌词和歌曲，同时歌曲内也有内嵌歌词

**Comment by Caij** [comment]
@CGBB0 可以下载这个试试 https://t.me/ppuremusic/186

**Comment by CGBB0** [comment]
这个歌词界面的处理方法挺好的，但是状态栏歌词那里显示的的依旧是翻译
![Screenshot_2023-06-29-17-15-15-965_com.caij.puremusic.jpg](https://github.com/pure-music/PureMusic/assets/101496448/2210fb07-8cf8-4748-86a0-5b23635396f5)

**Comment by Caij** [comment]
@CGBB0 再试试这个  https://t.me/ppuremusic/188

**Comment by CGBB0** [comment]
好像还是不太行

**Comment by Caij** [comment]
@CGBB0  再试试这个 https://t.me/c/1768936849/482  应该是可以了

**Comment by CGBB0** [comment]
可以了✓
