### ISSUE TITLE
违反RetroMusicPlayer GPLV3协议

### ISSUE THREAD

**Issue by vwps** [pure-music/PureMusic#4]
这个软件中发现大量RetroMusicPlayer源码内容，大量RetroMusicPlayer原作者原软件包名信息，并未在此软件内包括你的软件主页并未发现任何相关版权说明以及GPLV3开源说明，请作者做出完整解释。
GPLV3 写道：
For example, if you distribute copies of such a program, whether gratis or for a fee, you must pass on to the recipients the same freedoms that you received. You must make sure that they, too, receive or can get the source code. And you must show them these terms so they know their rights.
你做为一个多年的开发者，不可能不知道GPLV3协议。
明知软件为GPLV3协议而进行Copy改动并写道：Thanks RetroMusicPlayer UI，这不仅仅是UI而是大量移植，是在RetroMusicPlayer原项目直接改动，而不遵守GPLV3协议，明显违反。
比最近的CEC-IDE更**

**Comment by Caij** [comment]
@vwps 
说不同点：
RetroMusicPlayer基于系统播放器，Pure基于exoplayer，支持网络歌曲（云盘）播放。
RetroMusicPlayer仅管理本地歌曲文件，读取android系统媒体数据库， Pure使用sqldelight管理本地歌曲和云盘歌曲。
RetroMusicPlayer页面跳转基于Android官方的androidx.navigation，Pure用的是我自己写的独立的页面管理器。
RetroMusicPlayer歌手信息刮削用的deez的服务，Pure用的是spodify的服务。
RetroMusicPlayer图片加载和缓存逻辑和Pure不同。
RetroMusicPlayer的数据刷新依赖Android原生的Live Observer， Pure依赖EventBus。
**相同点**： 这部分我没有什么修改，另外这部分我也将在迁移。
UI和主题，交互相同。
歌曲队列的管理逻辑。

**Comment by Caij** [comment]
这里我的确是做的不对， 想钻个空子。想着后续全量迁移的，中间这段时间违反了协议。
* 在全量迁移之前，我不再发布任何新版本。
* 之前的非敏感代码我将开源。

**Comment by Caij** [comment]
开源非云盘、VIP和隐私库外的所有内容。
https://github.com/RetroMusicPlayer/RetroMusicPlayer/issues/1551 帮忙关闭关联内容
