### ISSUE TITLE
有时读不到WebDAV服务器上的文件

### ISSUE THREAD

**Issue by xuewen21** [pure-music/PureMusic#4]
我的webdav服务的地址是`https://xxx.xxx/dav`，这导致我如果选择根文件夹，就会读不到文件。我必须选择一个子文件夹，比如`music`文件夹，选完后显示的是`/dav/music/`，这才能正常使用。

**Comment by Caij** [comment]
@xuewen21 因为默认是读取4层文件夹，你的歌曲管理会很深层吗，也可以自己调节扫描层级？

**Comment by xuewen21** [comment]
> @xuewen21 因为默认是读取4层文件夹，你的歌曲管理会很深层吗，也可以自己调节扫描层级？

并不深，就放在music文件夹。有一个奇怪的现象：添加歌曲源时，如果我选择网盘的根目录，显示的结果是`/`，如果我选择`/music`文件夹，最后显示的是`/dav/music`，这应该是有问题的。

**Comment by xuewen21** [comment]
还有个问题，添加歌曲源后，首次读出来的音乐好像是按照网盘提供的默认排序显示的，不是文件名顺序，只有播放一遍后读出序号，才能恢复正常排序。

**Comment by Caij** [comment]
> 还有个问题，添加歌曲源后，首次读出来的音乐好像是按照网盘提供的默认排序显示的，不是文件名顺序，只有播放一遍后读出序号，才能恢复正常排序。

这个是由于播放后才能读取到歌曲的名字。 或者可以保证网盘里面的歌曲名是正确的

**Comment by Caij** [comment]
> > @xuewen21 因为默认是读取4层文件夹，你的歌曲管理会很深层吗，也可以自己调节扫描层级？
> 
> 并不深，就放在music文件夹。有一个奇怪的现象：添加歌曲源时，如果我选择网盘的根目录，显示的结果是`/`，如果我选择`/music`文件夹，最后显示的是`/dav/music`，这应该是有问题的。

路径只是显示问题，实际没什么问题， 扫描不出的话可以加我qq群我们单聊给安装包你测试一下

**Comment by Caij** [comment]
长时间无反馈先关闭，有问题可以再开启
