### ISSUE TITLE
什么时候能按专辑原始顺序播放啊?

### ISSUE THREAD

**Issue by ArmyDreamers** [pure-music/PureMusic#5]
歌曲都是乱的 难道要每次手动排序么?

**Comment by Caij** [comment]
试一下  [v1.33.1](https://github.com/pure-music/PureMusic/releases/tag/v1.33.1)版本

**Comment by ArmyDreamers** [comment]
> 试一下  [v1.33.1](https://github.com/pure-music/PureMusic/releases/tag/v1.33.1)版本

试了,还是一样的  还是按字母顺序排列的。

**Comment by Caij** [comment]
@ArmyDreamers 原始顺序指的是添加时间？

**Comment by ArmyDreamers** [comment]
> @ArmyDreamers 原始顺序指的是添加时间？

不是。就是专辑发行时的顺序

比如周杰伦的范特西专辑 
在网易云音乐里的歌曲顺序。

再说容易一点就按
你上传到网盘的无损音乐专辑
文件夹里歌曲名前面都会标1.2.3.的顺序,
不是字母顺序的。
现在这个app只能按字母顺序。

这个应该很容易实现吧。

**Comment by Caij** [comment]
> > @ArmyDreamers 原始顺序指的是添加时间？
> 
> 不是。就是专辑发行时的顺序
> 
> 比如周杰伦的范特西专辑 在网易云音乐里的歌曲顺序。
> 
> 再说容易一点就按 你上传到网盘的无损音乐专辑 文件夹里歌曲名前面都会标1.2.3.的顺序, 不是字母顺序的。 现在这个app只能按字母顺序。
> 
> 这个应该很容易实现吧。

歌曲编号需要读取歌曲标签信息，播放后会自动刷新的。或者前置通过文件命名设置编号。
https://caij.xyz/puremusic/faq/zh/

**Comment by ArmyDreamers** [comment]
> > > @ArmyDreamers 原始顺序指的是添加时间？
> > 
> > 不是。就是专辑发行时的顺序
> > 
> > 比如周杰伦的范特西专辑 在网易云音乐里的歌曲顺序。
> > 
> > 再说容易一点就按 你上传到网盘的无损音乐专辑 文件夹里歌曲名前面都会标1.2.3.的顺序, 不是字母顺序的。 现在这个app只能按字母顺序。
> > 
> > 这个应该很容易实现吧。
> 
> 歌曲编号需要读取歌曲标签信息，播放后会自动刷新的。或者前置通过文件命名设置编号。
> https://caij.xyz/puremusic/faq/zh/

问题解决。。。
原来藏得这么深。

**Comment by ArmyDreamers** [comment]
> > > @ArmyDreamers 原始顺序指的是添加时间？
> > 
> > 不是。就是专辑发行时的顺序
> > 
> > 比如周杰伦的范特西专辑 在网易云音乐里的歌曲顺序。
> > 
> > 再说容易一点就按 你上传到网盘的无损音乐专辑 文件夹里歌曲名前面都会标1.2.3.的顺序, 不是字母顺序的。 现在这个app只能按字母顺序。
> > 
> > 这个应该很容易实现吧。
> 
> 歌曲编号需要读取歌曲标签信息，播放后会自动刷新的。或者前置通过文件命名设置编号。
> https://caij.xyz/puremusic/faq/zh/

最新版本1.33.5 问题已解决
重新填了track-name-artist  顺序终于正确了。
