### ISSUE TITLE
希望增加更多音频格式支持

### ISSUE THREAD

**Issue by 99477204** [pure-music/PureMusic#7]
我有很多.ape格式的音乐，发现APP识别不到，希望开发者增加支持ape格式音乐

**Comment by www766** [comment]
放弃ape吧 都转成flac 怎么还不会玩音乐 用开源无损格式 闭源的格式解码器啥的要交专利费的要不侵权

**Comment by Caij** [comment]
有没有ape带tag的文件分享给我  @99477204

**Comment by 99477204** [comment]
> 放弃ape吧 都转成flac 怎么还不会玩音乐 用开源无损格式 闭源的格式解码器啥的要交专利费的要不侵权

太多，下载转码再上传太费时间

**Comment by 99477204** [comment]
> 有没有ape带tag的文件分享给我 @99477204

我是用音乐标签（MusicTag）匹配的

**Comment by Caij** [comment]
> > 有没有ape带tag的文件分享给我 @99477204
> 
> 我是用音乐标签（MusicTag）匹配的，链接为https://www.cnblogs.com/vinlxc/p/11347744.html

能搞个现成的文件分享给我吗

**Comment by 99477204** [comment]
> > > 有没有ape带tag的文件分享给我 @99477204
> > 
> > 
> > 我是用音乐标签（MusicTag）匹配的，链接为https://www.cnblogs.com/vinlxc/p/11347744.html
> 
> 能搞个现成的文件分享给我吗
请查收
https://drive.filen.io/f/a4db127b-ccc4-4171-8204-76a6823d4199#FzFXX4yTN08ojXJj6KuTxyvBoTLSXJWk

**Comment by Caij** [comment]
@99477204 https://github.com/pure-music/PureMusic/releases/tag/v1.34.0-beta9  试试新版
